export const languageNames = {
  "af-ZA": "Afrikaans (South Africa)",
  "am-ET": "Amharic (Ethiopia)",
  "ar-SA": "Arabic (Saudi Arabia)",
  "ar-001": "Arabic (World)",
  "az-AZ": "Azerbaijani (Azerbaijan)",
  "bg-BG": "Bulgarian (Bulgaria)",
  "bn-BD": "Bengali (Bangladesh)",
  "ca-ES": "Catalan (Spain)",
  "cs-CZ": "Czech (Czech Republic)",
  "cy-GB": "Welsh (United Kingdom)",
  "da-DK": "Danish (Denmark)",
  "de-DE": "German (Germany)",
  "el-GR": "Greek (Greece)",
  "en-AU": "English (Australia)",
  "en-GB": "English (United Kingdom)",
  "en-IE": "English (Ireland)",
  "en-IN": "English (India)",
  "en-US": "English (United States)",
  "en-ZA": "English (South Africa)",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexico)",
  "et-EE": "Estonian (Estonia)",
  "fa-IR": "Persian (Iran)",
  "fi-FI": "Finnish (Finland)",
  "fil-PH": "Filipino (Philippines)",
  "fr-CA": "French (Canada)",
  "fr-FR": "French (France)",
  "gu-IN": "Gujarati (India)",
  "he-IL": "Hebrew (Israel)",
  "hi-IN": "Hindi (India)",
  "hr-HR": "Croatian (Croatia)",
  "hu-HU": "Hungarian (Hungary)",
  "hy-AM": "Armenian (Armenia)",
  "id-ID": "Indonesian (Indonesia)",
  "is-IS": "Icelandic (Iceland)",
  "it-IT": "Italian (Italy)",
  "ja-JP": "Japanese (Japan)",
  "jv-ID": "Javanese (Indonesia)",
  "ka-GE": "Georgian (Georgia)",
  "kk-KZ": "Kazakh (Kazakhstan)",
  "km-KH": "Khmer (Cambodia)",
  "kn-IN": "Kannada (India)",
  "ko-KR": "Korean (South Korea)",
  "lo-LA": "Lao (Laos)",
  "lt-LT": "Lithuanian (Lithuania)",
  "lv-LV": "Latvian (Latvia)",
  "mk-MK": "Macedonian (North Macedonia)",
  "ml-IN": "Malayalam (India)",
  "mn-MN": "Mongolian (Mongolia)",
  "mr-IN": "Marathi (India)",
  "ms-MY": "Malay (Malaysia)",
  "my-MM": "Burmese (Myanmar)",
  "ne-NP": "Nepali (Nepal)",
  "nl-NL": "Dutch (Netherlands)",
  "no-NO": "Norwegian (Norway)",
  "pa-IN": "Punjabi (India)",
  "pl-PL": "Polish (Poland)",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "ro-RO": "Romanian (Romania)",
  "ru-RU": "Russian (Russia)",
  "si-LK": "Sinhala (Sri Lanka)",
  "sk-SK": "Slovak (Slovakia)",
  "sl-SI": "Slovenian (Slovenia)",
  "sq-AL": "Albanian (Albania)",
  "sr-RS": "Serbian (Serbia)",
  "su-ID": "Sundanese (Indonesia)",
  "sv-SE": "Swedish (Sweden)",
  "sw-KE": "Swahili (Kenya)",
  "ta-IN": "Tamil (India)",
  "te-IN": "Telugu (India)",
  "th-TH": "Thai (Thailand)",
  "tr-TR": "Turkish (Turkey)",
  "uk-UA": "Ukrainian (Ukraine)",
  "ur-PK": "Urdu (Pakistan)",
  "uz-UZ": "Uzbek (Uzbekistan)",
  "vi-VN": "Vietnamese (Vietnam)",
  "zh-CN": "Chinese (Mandarin)",
  "zh-HK": "Chinese (Hong Kong)",
  "zh-TW": "Chinese (Taiwan)",
  "zu-ZA": "Zulu (South Africa)",
  "nb-NO": "Norwegian Bokmål (Norway)",
  "nl-BE": "Dutch (Belgium)",
  "es-US": "Spanish (United States)",
  "yue-HK": "Cantonese (Hong Kong)",
  "in-ID": "Indonesian (Indonesia)",
  "iw-IL": "Hebrew (Israel)",
  ar: "Arabic",
  "bs-BA": "Bosnian (Bosnia and Herzegovina)",
  "bn-IN": "Bengali (India)",
  "en-NG": "English (Nigeria)",
  sr: "Serbian",
};
